/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CanoeHelper {
  export type WarrantStruct = {
    nonce: BigNumberish;
    validBefore: BigNumberish;
    validAfter: BigNumberish;
    verifyingSigner: AddressLike;
    signature: BytesLike;
  };

  export type WarrantStructOutput = [
    nonce: bigint,
    validBefore: bigint,
    validAfter: bigint,
    verifyingSigner: string,
    signature: string
  ] & {
    nonce: bigint;
    validBefore: bigint;
    validAfter: bigint;
    verifyingSigner: string;
    signature: string;
  };
}

export declare namespace PermitHelper {
  export type PermitStruct = {
    value: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
    isDaiStylePermit: boolean;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
  };

  export type PermitStructOutput = [
    value: bigint,
    nonce: bigint,
    deadline: bigint,
    isDaiStylePermit: boolean,
    v: bigint,
    r: string,
    s: string
  ] & {
    value: bigint;
    nonce: bigint;
    deadline: bigint;
    isDaiStylePermit: boolean;
    v: bigint;
    r: string;
    s: string;
  };
}

export interface RainbowRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eip712Domain"
      | "fillQuoteEthToToken"
      | "fillQuoteTokenToEth"
      | "fillQuoteTokenToEthWithPermit"
      | "fillQuoteTokenToToken"
      | "fillQuoteTokenToTokenWithPermit"
      | "name"
      | "owner"
      | "swapTargets"
      | "transferOwnership"
      | "updateSwapTargets"
      | "updateValidSigner"
      | "validSigners"
      | "version"
      | "withdrawEth"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "EthWithdrawn"
      | "OwnerChanged"
      | "SwapTargetAdded"
      | "SwapTargetRemoved"
      | "TokenWithdrawn"
      | "ValidSignerAdded"
      | "ValidSignerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteEthToToken",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEth",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToToken",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapTargets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSwapTargets",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValidSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "validSigners",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawEth",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteEthToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValidSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthWithdrawnEvent {
  export type InputTuple = [target: AddressLike, amount: BigNumberish];
  export type OutputTuple = [target: string, amount: bigint];
  export interface OutputObject {
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [newOwner: AddressLike, oldOwner: AddressLike];
  export type OutputTuple = [newOwner: string, oldOwner: string];
  export interface OutputObject {
    newOwner: string;
    oldOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapTargetAddedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapTargetRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    target: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, target: string, amount: bigint];
  export interface OutputObject {
    token: string;
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidSignerAddedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidSignerRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RainbowRouter extends BaseContract {
  connect(runner?: ContractRunner | null): RainbowRouter;
  waitForDeployment(): Promise<this>;

  interface: RainbowRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  fillQuoteEthToToken: TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEth: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEthWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToToken: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToTokenWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  swapTargets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSwapTargets: TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;

  updateValidSigner: TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;

  validSigners: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  version: TypedContractMethod<[], [string], "view">;

  withdrawEth: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fillQuoteEthToToken"
  ): TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEth"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEthWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToToken"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToTokenWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapTargets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSwapTargets"
  ): TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateValidSigner"
  ): TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validSigners"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawEth"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EthWithdrawn"
  ): TypedContractEvent<
    EthWithdrawnEvent.InputTuple,
    EthWithdrawnEvent.OutputTuple,
    EthWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "SwapTargetAdded"
  ): TypedContractEvent<
    SwapTargetAddedEvent.InputTuple,
    SwapTargetAddedEvent.OutputTuple,
    SwapTargetAddedEvent.OutputObject
  >;
  getEvent(
    key: "SwapTargetRemoved"
  ): TypedContractEvent<
    SwapTargetRemovedEvent.InputTuple,
    SwapTargetRemovedEvent.OutputTuple,
    SwapTargetRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ValidSignerAdded"
  ): TypedContractEvent<
    ValidSignerAddedEvent.InputTuple,
    ValidSignerAddedEvent.OutputTuple,
    ValidSignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidSignerRemoved"
  ): TypedContractEvent<
    ValidSignerRemovedEvent.InputTuple,
    ValidSignerRemovedEvent.OutputTuple,
    ValidSignerRemovedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EthWithdrawn(address,uint256)": TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;
    EthWithdrawn: TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "SwapTargetAdded(address)": TypedContractEvent<
      SwapTargetAddedEvent.InputTuple,
      SwapTargetAddedEvent.OutputTuple,
      SwapTargetAddedEvent.OutputObject
    >;
    SwapTargetAdded: TypedContractEvent<
      SwapTargetAddedEvent.InputTuple,
      SwapTargetAddedEvent.OutputTuple,
      SwapTargetAddedEvent.OutputObject
    >;

    "SwapTargetRemoved(address)": TypedContractEvent<
      SwapTargetRemovedEvent.InputTuple,
      SwapTargetRemovedEvent.OutputTuple,
      SwapTargetRemovedEvent.OutputObject
    >;
    SwapTargetRemoved: TypedContractEvent<
      SwapTargetRemovedEvent.InputTuple,
      SwapTargetRemovedEvent.OutputTuple,
      SwapTargetRemovedEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;

    "ValidSignerAdded(address)": TypedContractEvent<
      ValidSignerAddedEvent.InputTuple,
      ValidSignerAddedEvent.OutputTuple,
      ValidSignerAddedEvent.OutputObject
    >;
    ValidSignerAdded: TypedContractEvent<
      ValidSignerAddedEvent.InputTuple,
      ValidSignerAddedEvent.OutputTuple,
      ValidSignerAddedEvent.OutputObject
    >;

    "ValidSignerRemoved(address)": TypedContractEvent<
      ValidSignerRemovedEvent.InputTuple,
      ValidSignerRemovedEvent.OutputTuple,
      ValidSignerRemovedEvent.OutputObject
    >;
    ValidSignerRemoved: TypedContractEvent<
      ValidSignerRemovedEvent.InputTuple,
      ValidSignerRemovedEvent.OutputTuple,
      ValidSignerRemovedEvent.OutputObject
    >;
  };
}
