/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  CanoeHelper,
  CanoeHelperInterface,
} from "../../../contracts/libraries/CanoeHelper";

const _abi = [
  {
    inputs: [],
    name: "EIP712_CANOE_WARRANT_TYPE",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TYPEHASH_CANOE_WARRANT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610177610039600b82828239805160001a607314602c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100405760003560e01c806368b74d9e1461004557806395a9641f14610063575b600080fd5b61004d610079565b60405161005a91906100b8565b60405180910390f35b61006b610095565b60405190815260200161005a565b6040518060600160405280603b8152602001610107603b913981565b6040518060600160405280603b8152602001610107603b91398051906020012081565b602081526000825180602084015260005b818110156100e657602081860181015160408684010152016100c9565b506000604082850101526040601f19601f8301168401019150509291505056fe43616e6f6557617272616e742875696e74323536207061636b656456616c69646174696f6e446174612c6279746573333220646174614861736829a2646970667358221220c3b77210a10dee9cdc62e784c8569f05ca5e57ec57b6a5ae114cbbae950ada8264736f6c634300081b0033";

type CanoeHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CanoeHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CanoeHelper__factory extends ContractFactory {
  constructor(...args: CanoeHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CanoeHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CanoeHelper__factory {
    return super.connect(runner) as CanoeHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CanoeHelperInterface {
    return new Interface(_abi) as CanoeHelperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CanoeHelper {
    return new Contract(address, _abi, runner) as unknown as CanoeHelper;
  }
}
